---

- name: Load variables for the target system
  include_vars: "{{ item }}"
  with_first_found:
    - files:
      - "{{ ansible_distribution }}.yml"
      - "{{ ansible_os_family }}.yml"
      - "default.yml"
      paths: vars

- include: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- include: darwin.yml
  when: ansible_os_family == 'Darwin'

- name: Does NVM directory already exists?
  stat:
    path: "{{ nvm_dir }}"
  register: nvm_st
  changed_when: False

- name: Get installed NVM version
  shell: "git describe --tags `git rev-list --tags --max-count=1`" # noqa 303
  args:
    chdir: "{{ nvm_dir }}"
  register: nvm_installed_version
  when: nvm_st.stat.exists
  changed_when: False

- name: Is NVM running latest version?
  set_fact:
    nvm_version_match: "{{ nvm_installed_version.stdout == nvm_version }}"
  when: nvm_st.stat.exists

# Install NVM
- include: install.yml
  when: not nvm_st.stat.exists or not nvm_version_match

# Configure shell
- include: shell.yml
  when: nvm_shell_init

# Install default Node.js versions
- include: versions.yml
