name: Test

# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: Pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Install virtualenv v16.3.0 to fix ansible-lint install
        run: pip install virtualenv==16.3.0
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Run pre-commit
        run: pre-commit run -a
